name: release

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: publish
        uses: devcontainers/action@v1
        with:
          base-path-to-templates: './src'
          publish-templates: 'true'
          generate-docs: 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
